name: Generate Dataset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-dataset:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy absl-py sympy

    # Step 4: Run the dataset generation script
    - name: Generate dataset
      run: |
        python -m mathematics_dataset.generate_to_file --output_dir=algebra --filter=algebra

    # Step 5: Upload generated dataset to GitHub artifact
    - name: Upload dataset artifact
      uses: actions/upload-artifact@v3
      with:
        name: algebra-dataset
        path: ./algebra/
